### PR TITLE
fix: make build parralel friendly

### PR DESCRIPTION
**Pull request by 12rambau**
superceed #10

### CODE REVIEW

**Comment by benjaoming** [comment]
This didn't include the parts from #10 that skips adding videos to irrelevant formats? Was that on purpose?

```
        latex=ignore_node,
        text=ignore_node,
        man=ignore_node,
        texifo=ignore_node,
```

**Comment by benjaoming** [comment]
Ah, it's in #16 :+1:

**Comment by 12rambau** [comment]
I'm going to use squash merges from now so I try to split things up

**Comment by 12rambau** [comment]
TBH the youtube solution in combination with sphinxcontrib-youtube works quite well for huge videos. Note that github LFS is not supported in RDT (last time I checked). Note that Drive videos behave the same as a youtube video and ca thus be wired the same way.

**Comment by benjaoming** [comment]
Git LFS is supported on RTD by extending the build process: https://docs.readthedocs.io/en/stable/build-customization.html#support-git-lfs-large-file-storage

**Comment by 12rambau** [comment]
that's perfect, it seems I'm confusing with another service ;-)

**Comment by benjaoming** [comment]
I'm not so clear in the description on https://github.com/benjaoming/anti-pattern-sphinx-video-downloader, but I suggest basically to have 2 repos active for documentation with video:

1) Repo for the documentation: Because it's documentation, it changes often and is built often, so we don't want large files here. During builds, we download videos from repo 2 (and can store them in a local cache if possible).

2) Repo/resource for videos: Here, we store and publish the videos. This can be both Git and Google Drive, depending on what level of archive history that you need.

**Pull request merged**
